services:
  dremio-mcp:
    build: 
      context: ./services/dremio-mcp
      dockerfile: Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME:-dremio-mcp-docker}_dremio-mcp_1"
    environment:
      - DREMIO_URI=${DREMIO_URI}
      - EXTRA_ARGS=${MCP_EXTRA_ARGS:-}
    volumes:
      - token-volume:/app/tokens:ro
    depends_on:
      - token-refresher
    networks:
      - dremio-mcp-network
    stdin_open: true
    tty: true
    extra_hosts:
      - "dremio.dev.serraict.me:host-gateway"

  token-refresher:
    build:
      context: ./services/token-refresher
      dockerfile: Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME:-dremio-mcp-docker}_token-refresher_1"
    environment:
      - DREMIO_URI=${DREMIO_URI}
      - DREMIO_USERNAME=${DREMIO_USERNAME}
      - DREMIO_PASSWORD=${DREMIO_PASSWORD}
      - REFRESH_INTERVAL=${REFRESH_INTERVAL:-72000}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-dremio-mcp-docker}
    volumes:
      - token-volume:/app/tokens:rw
    networks:
      - dremio-mcp-network
    extra_hosts:
      - "dremio.dev.serraict.me:host-gateway"

volumes:
  token-volume:
    driver: local

networks:
  dremio-mcp-network:
    driver: bridge
